### ISSUE TITLE
testers: Group test results with datasets

### ISSUE THREAD

**Issue by adisandro** [MarkUsProject/markus-autotesting#73]
With testers that support datasets, it would be nice to have a way to tell MarkUs about such "grouped" tests, so that a per-dataset/per-test summary can be generated in the interface.

**Comment by mishaschwartz** [comment]
This is no longer a pattern that the autotester supports. Test groups are implemented and _can_ be used to map tests to datasets but there is no longer an explicit mapping of datasets to tests (like there was in the deprecated SQL and JDBC testers)
